### PR TITLE
Fix analytics toggle

### LINKED ISSUE #443: Toggle for opt in analytics doesn't turn on after turning it off once
**Describe the bug**
In the Settings > Preferences, there's an option for Opt-in-analytics. This is turned on by default but we're unable to turn it on once we turn it off no matter how many times we try to click it. This issue exists in android app from google playstore. 

**To Reproduce**
1. Open the android app and go to Settings.
2. Under the PREFERENCES, there's an option to toggle - "Help Improve Friend by sharing anonymized analytics data"
3. Turn it off once and then you can't turn it back on even if you try clicking it.

**Expected behavior**
User should be able to turn it on and off by clicking it

**Screenshots**
image

**Smartphone (please complete the following information):**
 - Device: RedMI
 - OS: Android
 - Version 12

### PR DESCRIPTION
**Pull request by mdmohsin7**
Fixes #443

### CODE REVIEW

File: apps/AppWithWearable/lib/pages/settings/page.dart [hunk 1]
```diff
@@ -102,7 +102,7 @@ class _SettingsPageState extends State<SettingsPage> {
                   ...getPreferencesWidgets(
                     onOptInAnalytics: () {
                       setState(() {
-                        optInAnalytics = false;
+                        optInAnalytics = !SharedPreferencesUtil().optInAnalytics;
                         SharedPreferencesUtil().optInAnalytics = !SharedPreferencesUtil().optInAnalytics;
```
Comment (francip) [inline apps/AppWithWearable/lib/pages/settings/page.dart:106]: [nitpick] Could've used the value of the variable above. (Not that the compiler won't be smart enough and optimize this...)

**Review by francip — APPROVED** [review]
